# Generated by Django 5.1.5 on 2025-02-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='refeicoes_livres',
            field=models.FloatField(),
        ),
    ]
